### PR TITLE
move test requirements into build requirements

### PR DESCRIPTION
**Pull request by bw4sz**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by henrykironde** [comment]
@bw4sz can you re run this, Keras-resnet is merged

**Comment by henrykironde** [comment]
@bw4sz these files should be in the source distribution
`tests/data/`
I do not see them in the distribution
We can add the paths here 
`https://github.com/weecology/DeepForest/blob/master/MANIFEST.in`

**Comment by henrykironde** [comment]
@bw4sz I think We can put imports in the test section, with no command to run

**Comment by bw4sz** [comment]
@henrykironde i'm merging into master since this actually has a install of deepforest with dependencies. I think we should move the other questions on python 3.8 and (windows?) to a new PR.

**Review by henrykironde — COMMENTED** [review]
Great work @bw4sz

**Pull request merged**
